- name: condition demo
  hosts: localhost
  connection: local
  vars:
    IS_LIVE: true
  tasks:
    - name: print the task content
      ansible.builtin.debug:
        msg: "this is msg based on condition"
      when: IS_LIVE