- name: gathering facts
  hosts: localhost
  connection: local
  tasks:
  - name: check redhat or not
    ansible.builtin.debug:
        msg: "Yes, package manager is RedHat"
    when: ansible_facts.os_family == "RedHat"

  - name: check Debian or not
    ansible.builtin.debug:
      msg: "Yes, package manager is Debian"
    when: ansible_facts.os_family == "Debian"